### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by kyash227** [kyash227/college-website#1]
PLz add a CSS file in order add custom dynamic animated webpage.

**Comment by prabincankod** [comment]
I can do that easily. Assign this to me.

**Comment by ORKO06** [comment]
I would like to work on this

**Comment by Ujjwal-Gupta-web** [comment]
Hey, please demonstrate the issue more clearly.
I am unable to get the issue.
I would like to contribute to this.
@kyash227

**Comment by Sudipta2002** [comment]
Kindly assign this work to me
